PAGE DE REMINDS, ON POURRA AJOUTER SUPPRIMER DES RAPPELS
    LES RAPPELS POURRONT SOIT ÊTRE A UNE DATE DONNE (LE 17/05/2021 A 10H12) DONC DEUX INPUT TYPE DATE ET TIME, 
    SOIT DANS UN TEMPS DONNE (DANS 5J, 3H ET 5MIN) AVEC PLUSIEURS INPUT DE NOMBRE ?
L'UTILISATEUR POURRA ATTRIBUER UN NOM A SON RAPPEL POUR LE DIFFERENCIER DES AUTRES